# 告訴 Cloudflare Pages 你的 Astro 專案建置後檔案在哪裡
# 注意路徑！因為你的專案在子目錄中。
pages_build_output_dir = "./astro-clinical-platform/dist"

# 設置一個未來的日期以啟用最新功能
compatibility_date = "2025-07-30"

# 啟用 Node.js 相容性模式，解決 MessageChannel 錯誤
compatibility_flags = ["nodejs_compat"]