version: 2
updates:
  # NPM 依賴更新
  - package-ecosystem: "npm"
    directory: "/astro-clinical-platform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Taipei"
    open-pull-requests-limit: 10
    reviewers:
      - "medical-platform-team"
    assignees:
      - "medical-platform-team"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # 醫療平台的特殊考量
    ignore:
      # 忽略主要框架的 major 版本更新，需要手動審查
      - dependency-name: "astro"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
    # 自動合併安全更新
    auto-merge:
      enabled: true
      merge-method: "squash"
    # 分組相關更新
    groups:
      astro:
        patterns:
          - "@astrojs/*"
          - "astro"
      react:
        patterns:
          - "react*"
          - "@types/react*"
      testing:
        patterns:
          - "vitest"
          - "@vitest/*"
          - "@testing-library/*"
          - "jest*"
      linting:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier*"
      medical-deps:
        patterns:
          - "mermaid"
          - "chart.js"
          - "fuse.js"

  # GitHub Actions 更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Taipei"
    open-pull-requests-limit: 5
    reviewers:
      - "medical-platform-team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
    groups:
      actions:
        patterns:
          - "actions/*"
          - "github/*"