name: 🆕 新增衛教內容請求
description: 請求新增醫療衛教文章或內容
title: "[內容請求] "
labels: ["content-request", "needs-triage"]
assignees:
  - content-manager

body:
  - type: markdown
    attributes:
      value: |
        感謝您提出新增醫療衛教內容的請求！請填寫以下資訊，幫助我們更好地了解您的需求。

  - type: input
    id: content-title
    attributes:
      label: 建議的文章標題
      description: 請提供您希望新增的衛教文章標題
      placeholder: 例如：心房顫動的診斷與治療
    validations:
      required: true

  - type: dropdown
    id: medical-specialty
    attributes:
      label: 醫療專科分類
      description: 請選擇最相關的醫療專科
      options:
        - 心臟科 (Cardiology)
        - 神經科 (Neurology)
        - 小兒科 (Pediatrics)
        - 急診科 (Emergency Medicine)
        - 骨科 (Orthopedics)
        - 內分泌科 (Endocrinology)
        - 腸胃科 (Gastroenterology)
        - 呼吸科 (Pulmonology)
        - 腎臟科 (Nephrology)
        - 精神科 (Psychiatry)
        - 皮膚科 (Dermatology)
        - 眼科 (Ophthalmology)
        - 耳鼻喉科 (ENT)
        - 婦產科 (Obstetrics & Gynecology)
        - 泌尿科 (Urology)
        - 其他
    validations:
      required: true

  - type: dropdown
    id: content-type
    attributes:
      label: 內容類型
      description: 請選擇最適合的內容類型
      options:
        - 疾病介紹與症狀
        - 診斷方法與檢查
        - 治療選項與方法
        - 預防保健指導
        - 用藥指導與安全
        - 復健與照護
        - 急救與緊急處理
        - 營養與飲食建議
        - 生活方式調整
        - 其他
    validations:
      required: true

  - type: dropdown
    id: target-audience
    attributes:
      label: 目標讀者群
      description: 這篇文章主要針對哪些讀者？
      options:
        - 一般民眾
        - 患者及家屬
        - 高風險族群
        - 特定年齡層（兒童）
        - 特定年齡層（青少年）
        - 特定年齡層（成人）
        - 特定年齡層（老年人）
        - 醫療從業人員
        - 照護者
        - 其他
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: 緊急程度
      description: 此內容的緊急程度如何？
      options:
        - 🔴 緊急 (1週內) - 涉及公共健康安全
        - 🟡 重要 (1個月內) - 常見疾病或重要資訊
        - 🟢 一般 (3個月內) - 補充性或預防性資訊
        - ⚪ 低優先級 (6個月內) - 非緊急的一般資訊
    validations:
      required: true

  - type: textarea
    id: content-outline
    attributes:
      label: 內容大綱
      description: 請簡要描述希望包含的主要內容
      placeholder: |
        例如：
        1. 什麼是心房顫動
        2. 常見症狀和徵象
        3. 診斷方法
        4. 治療選項
        5. 生活管理建議
        6. 何時需要就醫
    validations:
      required: true

  - type: textarea
    id: background-reason
    attributes:
      label: 請求背景與原因
      description: 為什麼需要這篇文章？有什麼特殊背景或原因嗎？
      placeholder: |
        例如：
        - 最近有很多患者詢問相關問題
        - 發現現有資訊不夠完整
        - 配合最新的臨床指引更新
        - 回應社群媒體上的常見疑問

  - type: input
    id: reference-sources
    attributes:
      label: 建議參考資料
      description: 如果您有建議的參考資料或資訊來源，請提供
      placeholder: 例如：最新的臨床指引、重要研究論文、官方建議等

  - type: dropdown
    id: has-expert
    attributes:
      label: 是否有專家資源
      description: 您是否能提供相關的醫療專家進行內容審核？
      options:
        - 是，我可以提供專家聯絡方式
        - 是，但需要協助聯繫
        - 否，需要平台安排專家審核
        - 不確定
    validations:
      required: true

  - type: input
    id: expert-contact
    attributes:
      label: 專家聯絡資訊（如有）
      description: 如果您有相關專家的聯絡方式，請提供
      placeholder: 專家姓名、職稱、聯絡方式（可選）

  - type: checkboxes
    id: additional-requirements
    attributes:
      label: 額外需求
      description: 請勾選任何額外的需求或特殊要求
      options:
        - label: 需要多語言版本
        - label: 需要圖表或插圖
        - label: 需要影片或多媒體內容
        - label: 需要互動式元素
        - label: 需要可下載的資料
        - label: 需要社群媒體素材
        - label: 需要列印版本優化

  - type: textarea
    id: additional-notes
    attributes:
      label: 其他備註
      description: 任何其他需要說明的事項
      placeholder: 其他特殊要求、注意事項或相關資訊

  - type: checkboxes
    id: terms
    attributes:
      label: 確認事項
      description: 請確認您了解以下事項
      options:
        - label: 我了解所有醫療內容都需要經過專業醫療人員審核
          required: true
        - label: 我了解內容製作可能需要一定的時間進行研究和審核
          required: true
        - label: 我同意提供的資訊可能會被用於內容製作參考
          required: true