name: 🐛 內容錯誤回報
description: 回報醫療衛教內容中的錯誤或問題
title: "[內容錯誤] "
labels: ["content-error", "needs-review", "high-priority"]
assignees:
  - content-manager
  - medical-advisors

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **重要提醒**: 如果您發現的是緊急醫療安全問題，請立即聯絡我們的緊急聯絡人，不要僅依賴此表單。
        
        感謝您幫助我們改善醫療衛教內容的品質！請詳細描述您發現的問題。

  - type: input
    id: article-url
    attributes:
      label: 問題文章連結
      description: 請提供發現問題的文章完整網址
      placeholder: https://example.com/education/article-name
    validations:
      required: true

  - type: input
    id: article-title
    attributes:
      label: 文章標題
      description: 請提供文章的完整標題
      placeholder: 例如：心房顫動的診斷與治療
    validations:
      required: true

  - type: dropdown
    id: error-type
    attributes:
      label: 錯誤類型
      description: 請選擇最符合的錯誤類型
      options:
        - 🚨 醫療資訊錯誤 - 可能影響患者安全
        - 💊 藥物資訊錯誤 - 劑量、用法或副作用錯誤
        - 📊 數據或統計錯誤 - 錯誤的數字或百分比
        - 🔗 參考文獻錯誤 - 引用錯誤或連結失效
        - ✏️ 文字錯誤 - 錯字、語法或表達問題
        - 🖼️ 圖片或圖表錯誤 - 圖像內容不正確
        - 🔄 過時資訊 - 內容已不符合最新醫學標準
        - 🎯 誤導性內容 - 可能造成誤解的表述
        - 🔧 技術問題 - 格式、連結或顯示問題
        - 其他
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 嚴重程度
      description: 請評估此錯誤的嚴重程度
      options:
        - 🔴 嚴重 - 可能危及患者安全或造成重大誤解
        - 🟡 中等 - 影響內容準確性但不會造成立即危險
        - 🟢 輕微 - 小錯誤但不影響主要資訊
    validations:
      required: true

  - type: textarea
    id: error-description
    attributes:
      label: 錯誤詳細描述
      description: 請詳細描述您發現的錯誤
      placeholder: |
        請包含：
        1. 錯誤的具體位置（段落、章節）
        2. 錯誤的內容是什麼
        3. 正確的內容應該是什麼
        4. 您如何發現這個錯誤
    validations:
      required: true

  - type: textarea
    id: incorrect-content
    attributes:
      label: 錯誤內容（原文）
      description: 請複製貼上有問題的原始內容
      placeholder: 請直接複製貼上文章中有問題的文字內容
    validations:
      required: true

  - type: textarea
    id: correct-content
    attributes:
      label: 建議的正確內容
      description: 如果您知道正確的內容，請提供
      placeholder: 請提供您認為正確的內容或修正建議

  - type: textarea
    id: evidence-sources
    attributes:
      label: 支持證據或資料來源
      description: 請提供支持您修正建議的證據或資料來源
      placeholder: |
        例如：
        - 最新的臨床指引
        - 權威醫學期刊文章
        - 官方醫療機構建議
        - 專業醫學會聲明

  - type: input
    id: reporter-background
    attributes:
      label: 回報者背景（可選）
      description: 您的專業背景有助於我們評估回報的可信度
      placeholder: 例如：醫師、護理師、藥師、患者、一般民眾等

  - type: dropdown
    id: how-discovered
    attributes:
      label: 如何發現此錯誤
      description: 您是如何發現這個錯誤的？
      options:
        - 專業知識判斷
        - 與其他資料來源比對
        - 臨床經驗不符
        - 患者或同事指出
        - 學術研究發現
        - 官方指引更新
        - 其他醫療網站比較
        - 其他

  - type: checkboxes
    id: impact-assessment
    attributes:
      label: 可能影響評估
      description: 請勾選此錯誤可能造成的影響
      options:
        - label: 可能影響患者治療決策
        - label: 可能造成用藥安全問題
        - label: 可能延誤就醫時機
        - label: 可能造成不必要的恐慌
        - label: 可能影響預防措施執行
        - label: 可能誤導家屬照護方式
        - label: 影響相對較小

  - type: textarea
    id: additional-context
    attributes:
      label: 其他相關資訊
      description: 任何其他有助於我們理解和修正此錯誤的資訊
      placeholder: |
        例如：
        - 相關的其他文章也有類似問題
        - 這個錯誤在社群中引起討論
        - 與最新研究發現不符
        - 其他需要注意的事項

  - type: input
    id: contact-info
    attributes:
      label: 聯絡方式（可選）
      description: 如果我們需要進一步確認細節，可以如何聯絡您？
      placeholder: 電子郵件或其他聯絡方式（可選）

  - type: checkboxes
    id: urgency-confirmation
    attributes:
      label: 緊急程度確認
      description: 請確認此錯誤的處理優先級
      options:
        - label: 🚨 這是緊急的醫療安全問題，需要立即處理
        - label: ⚡ 這是重要問題，建議儘快處理
        - label: 📝 這是一般錯誤，可以按正常流程處理

  - type: checkboxes
    id: terms
    attributes:
      label: 確認事項
      description: 請確認您了解以下事項
      options:
        - label: 我確認提供的資訊準確無誤
          required: true
        - label: 我了解此回報將由醫療專業人員審核
          required: true
        - label: 我同意提供的資訊可能會被用於內容改善
          required: true