# Cloudflare Pages 配置檔案
name = "astro-clinical-platform"
compatibility_date = "2024-01-15"

# Pages 專案設定
[env.production]
name = "astro-clinical-platform"
compatibility_date = "2024-01-15"

# 環境變數（在 Cloudflare Dashboard 中設定實際值）
[env.production.vars]
NODE_VERSION = "20"
NPM_VERSION = "10"

# 建置設定
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# 函數設定（如果需要）
[[env.production.services]]
binding = "DB"
service = "astro-clinical-db"

# KV 命名空間（用於快取）
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# R2 儲存（用於媒體檔案）
[[env.production.r2_buckets]]
binding = "MEDIA"
bucket_name = "astro-clinical-media"
preview_bucket_name = "astro-clinical-media-preview"

# 自訂域名設定
[env.production.routes]
patterns = ["astro-clinical-platform.com/*", "www.astro-clinical-platform.com/*"]
zone_name = "astro-clinical-platform.com"

# 開發環境設定
[env.development]
name = "astro-clinical-platform-dev"
compatibility_date = "2024-01-15"

[env.development.vars]
NODE_VERSION = "20"
NPM_VERSION = "10"