# Wrangler configuration for Cloudflare Pages
name = "ent-clinic-pro"
compatibility_date = "2024-07-29"

# Pages configuration
[env.production]
compatibility_date = "2024-07-29"

# KV bindings for session storage
[[env.production.kv_namespaces]]
binding = "SESSION"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# Environment variables
[env.production.vars]
NODE_ENV = "production"