name: 🏷️ PR 自動標籤

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    name: 🏷️ 自動添加標籤
    
    steps:
    - name: 應用標籤
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml

    - name: 分析 PR 內容並添加特殊標籤
      uses: actions/github-script@v6
      with:
        script: |
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });
          
          const title = pr.title.toLowerCase();
          const body = pr.body ? pr.body.toLowerCase() : '';
          const labels = [];
          
          // 根據 PR 標題和內容分析添加標籤
          
          // PR 類型標籤
          if (title.includes('新增') || title.includes('new') || title.includes('add')) {
            labels.push('type: new-content');
          }
          
          if (title.includes('更新') || title.includes('update') || title.includes('修改')) {
            labels.push('type: content-update');
          }
          
          if (title.includes('修正') || title.includes('fix') || title.includes('錯誤')) {
            labels.push('type: bug-fix');
          }
          
          if (title.includes('翻譯') || title.includes('translation') || title.includes('多語言')) {
            labels.push('type: translation');
          }
          
          // 優先級標籤
          if (title.includes('緊急') || title.includes('urgent') || title.includes('critical')) {
            labels.push('priority: high');
          }
          
          if (title.includes('重要') || title.includes('important')) {
            labels.push('priority: medium');
          }
          
          // 特殊關注標籤
          if (body.includes('藥物') || body.includes('medication') || body.includes('drug')) {
            labels.push('needs-pharmacist-review');
          }
          
          if (body.includes('手術') || body.includes('surgery') || body.includes('operation')) {
            labels.push('needs-surgeon-review');
          }
          
          if (body.includes('兒童') || body.includes('child') || body.includes('pediatric')) {
            labels.push('needs-pediatrician-review');
          }
          
          if (body.includes('心理') || body.includes('mental') || body.includes('psychiatric')) {
            labels.push('needs-psychiatrist-review');
          }
          
          if (body.includes('營養') || body.includes('nutrition') || body.includes('diet')) {
            labels.push('needs-nutritionist-review');
          }
          
          if (body.includes('復健') || body.includes('rehabilitation') || body.includes('physical therapy')) {
            labels.push('needs-physiotherapist-review');
          }
          
          if (body.includes('護理') || body.includes('nursing') || body.includes('care')) {
            labels.push('needs-nurse-review');
          }
          
          // 品質相關標籤
          if (body.includes('品質檢查') || body.includes('quality check')) {
            labels.push('quality-related');
          }
          
          if (body.includes('無障礙') || body.includes('accessibility')) {
            labels.push('accessibility-related');
          }
          
          if (body.includes('參考文獻') || body.includes('references')) {
            labels.push('references-related');
          }
          
          // 應用標籤
          if (labels.length > 0) {
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labels
            });
          }

    - name: 檢查是否需要特殊審核
      uses: actions/github-script@v6
      with:
        script: |
          const { data: files } = await github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });
          
          const reviewers = new Set();
          const labels = [];
          
          // 分析變更的檔案
          files.forEach(file => {
            const filename = file.filename.toLowerCase();
            const patch = file.patch ? file.patch.toLowerCase() : '';
            
            // 檢查是否涉及敏感醫療內容
            const sensitiveKeywords = [
              'medication', 'drug', 'prescription', 'dosage',
              'surgery', 'operation', 'procedure',
              'emergency', 'critical', 'urgent',
              'diagnosis', 'treatment', 'therapy'
            ];
            
            const hasSensitiveContent = sensitiveKeywords.some(keyword => 
              filename.includes(keyword) || patch.includes(keyword)
            );
            
            if (hasSensitiveContent) {
              labels.push('needs-medical-review');
              reviewers.add('medical-advisors');
            }
            
            // 檢查專科特定內容
            if (filename.includes('cardiology') || patch.includes('heart') || patch.includes('cardiac')) {
              reviewers.add('cardiology-reviewer');
            }
            
            if (filename.includes('neurology') || patch.includes('brain') || patch.includes('neurological')) {
              reviewers.add('neurology-reviewer');
            }
            
            if (filename.includes('pediatrics') || patch.includes('child') || patch.includes('infant')) {
              reviewers.add('pediatrics-reviewer');
            }
            
            if (filename.includes('emergency') || patch.includes('emergency') || patch.includes('urgent')) {
              reviewers.add('emergency-reviewer');
            }
            
            if (filename.includes('orthopedics') || patch.includes('bone') || patch.includes('joint')) {
              reviewers.add('orthopedics-reviewer');
            }
          });
          
          // 應用標籤
          if (labels.length > 0) {
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labels
            });
          }
          
          // 請求審核者
          if (reviewers.size > 0) {
            try {
              await github.rest.pulls.requestReviewers({
                pull_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                reviewers: Array.from(reviewers)
              });
            } catch (error) {
              console.log('無法自動指派審核者:', error.message);
            }
          }